# Generated by Django 5.1.1 on 2024-09-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_images/avatar.svg', null=True, upload_to='profile_images'),
        ),
    ]
